
- hosts: localhost
  connection: local

  tasks:
    - name: Create an EC2 key
      ec2_key:

        name: ozamodaz
        region: eu-central-1
        key_material: "{{ item }}"
      with_file: ~/.ssh/id_rsa.pub

    - name: Provision a set of instances
#      rds:
#        command: create
#        region: eu-central-1
#        instance_name: new-database
#        db_engine: MySQL
#        size: 10
#        instance_type: db.t2.micro
#        username: mysql_admin
#        password: 1nsecure

      ec2:
         key_name: ozamodaz
         instance_type: t2.micro
         image: ami-87564feb
         vpc_subnet_id: subnet-95f283ee
         region: eu-central-1
         assign_public_ip: yes
         wait: true
         count_tag: Test
         exact_count: 1
      register: ec2


    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=hosts
      with_items: ec2.instances

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=600 state=started
      with_items: ec2.instances


- hosts: hosts
  become: True
  remote_user: ubuntu
  roles:
    - app

- hosts: hosts
  become: False
  remote_user: "{{ username }}"
  roles:
    - django

- hosts: hosts
  become: True
  remote_user: ubuntu
  roles:
    - verify
