---

- name: Create virtualenv
  pip: virtualenv={{ project_dir }}/virtualenv name=djangocms-installer

- name: Install Django-CMS
  shell: ". {{ project_dir }}/virtualenv/bin/activate &&
  djangocms  --i18n yes --use-tz yes --timezone UTC --reversion yes --permissions yes --languages en --django-version stable --cms-version stable --parent-dir {{ project_dir }}/{{ app_name }} --bootstrap no --starting-page yes --no-input --no-sync --no-user --utc --db mysql://raccoon:raccoon@comein.space/rccngng app"

#- name: Run Django-CMS built-in server
#  shell: ". {{ project_dir }}/virtualenv/bin/activate && python {{ project_dir }}/{{ app_name }}/manage.py runserver 0.0.0.0:8081"

- name: Install uwsgi
  pip: virtualenv={{ project_dir }}/virtualenv name=uwsgi

- name: Configure static files
  replace: dest={{ project_dir }}/{{ app_name }}/app/settings.py regexp='^STATIC_ROOT\ =\ os\.path.join\(DATA_DIR,\ 'static'\)' replace='STATIC_ROOT = os.path.join(BASE_DIR, 'static')' backup=yes

- name: Run collectstatic
  django_manage: command=collectstatic app_path={{ project_dir }}/{{ app_name }} virtualenv={{ project_dir }}/virtualenv

#- name: Run uwsgi (run as user - {{ username }})
#  shell: ". {{ project_dir }}/virtualenv/bin/activate && screen -dmS {{  app_name }} uwsgi --ini {{ project_dir }}/uwsgi.ini"
