---

- name: Register host to make vars visible
  add_host: hostname=localhost groups=hosts

- name: Create an ec2 key from your .pub key
  ec2_key:
    name: "{{ username }}"
    region: "{{ region }}"
    key_material: "{{ item }}"
  with_file: "{{ pub_key_file }}"

- name: Create ec2 security group
  ec2_group:
    name: "allow-inbound-ssh-http-https"
    description: Allow Inbound Traffic
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0

- name: Creating EC2 instance
  ec2:
     key_name: "{{ username }}"
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ vpc_subnet_id}}"
     group: "allow-inbound-ssh-http-https"
     region: "{{ region }}"
     assign_public_ip: yes
     wait: true
     count_tag:
       Name: "{{ app_name }}"
     exact_count: 1
  register: ec2

- name: Add all instance public IPs to host group
  add_host: hostname={{ item.public_ip }} groups=hosts,app
  with_items: ec2.instances

- name: Wait for SSH to come up
  wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=600 state=started
  with_items: ec2.instances
